### ISSUE TITLE
Merge Drexel's Enhancements and Release

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/gwlf-e#82]
- [x] Generate test cases (GMS files)
- [x] Run against current GWLF-E and time and save results
- [x] Run against Drexel's PR #81 and compare with saved timings and results
- [x] Optimize dependencies #83
- [x] If successful and faster, merge the PR
- [x] Make a new release

**Comment by rajadain** [comment]
I've developed a subbasin timing baseline here:

https://docs.google.com/spreadsheets/d/1-diq5rQDTnGZf2N91ld10pMXf7h4NyiK_EUu4nZE4c0/edit?usp=sharing

Trying to install the fork and run the numbers with that but running instal installation issues. Will look more into them tomorrow.

**Comment by rajadain** [comment]
I've been observing the timing by running subbasin on specified shapes locally and then diffing the job create and delivery times in the database like so:

```sql
SELECT id, created_at, EXTRACT(EPOCH FROM (delivered_at - created_at)) AS "time_s"
FROM core_job
WHERE result LIKE '{"Loads": [{"Source":%' -- subbasin GWLF-E jobs have this signature
ORDER BY id DESC
LIMIT 10;
```

**Comment by rajadain** [comment]
Installation succeeded after adding `g++` to the worker VM and changing `requirements.txt` as follows:

```diff
diff --git a/src/mmw/mmw/settings/base.py b/src/mmw/mmw/settings/base.py
index 6b312729..808e71f0 100644
--- a/src/mmw/mmw/settings/base.py
+++ b/src/mmw/mmw/settings/base.py
@@ -122,6 +122,8 @@ CELERY_BROKER_URL = 'redis://{0}:{1}/2'.format(
 
 CELERY_IMPORTS = (
     # Submodule task is not always autodiscovered
+    'apps.geoprocessing_api.tasks',
+    'apps.modeling.tasks',
     'apps.modeling.mapshed.tasks',
 )
 CELERY_ACCEPT_CONTENT = ['json']
diff --git a/src/mmw/requirements/base.txt b/src/mmw/requirements/base.txt
index 8edf5ee4..29851658 100644
--- a/src/mmw/requirements/base.txt
+++ b/src/mmw/requirements/base.txt
@@ -15,7 +15,6 @@ cryptography==2.1.4
 pyOpenSSL==17.4.0
 markdown==2.6.9
 tr55==1.3.0
-gwlf-e==0.6.3
 requests[security]==2.9.1
 rollbar==0.13.8
 retry==0.9.1
@@ -24,8 +23,17 @@ https://bitbucket.org/jurko/suds/get/94664ddd46a6.tar.gz#egg=suds-jurko
 django_celery_results==1.0.1
 pandas==0.22.0
 git+git://github.com/emiliom/ulmo@wml_values_md#egg=ulmo
-numpy==1.13.0
+numpy==1.14.3
 hs_restclient==1.2.10
 six==1.11.0
 fiona==1.7.11
 timeout-decorator==0.4.0
+certifi==2018.4.16
+enum34==1.1.6
+funcsigs==1.0.2
+llvmlite==0.23.2
+mock==2.0.0
+nose==1.3.7
+numba==0.38.0
+singledispatch==3.4.0.3
+git+git://github.com/drexeleds/gwlf-e@develop#egg=gwlf-e
```

However, when I try to start Celery, I get this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/celery/__main__.py", line 14, in main
    _main()
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/worker.py", line 221, in run_from_argv
    return self(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 244, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/bin/worker.py", line 255, in run
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/worker.py", line 94, in __init__
    self.app.loader.init_worker()
  File "/usr/local/lib/python2.7/dist-packages/celery/loaders/base.py", line 116, in init_worker
    self.import_default_modules()
  File "/usr/local/lib/python2.7/dist-packages/celery/loaders/base.py", line 111, in import_default_modules
    return [self.import_task_module(m) for m in self.default_modules]
  File "/usr/local/lib/python2.7/dist-packages/celery/loaders/base.py", line 97, in import_task_module
    return self.import_from_cwd(module)
  File "/usr/local/lib/python2.7/dist-packages/celery/loaders/base.py", line 106, in import_from_cwd
    package=package,
  File "/usr/local/lib/python2.7/dist-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/usr/local/lib/python2.7/dist-packages/celery/loaders/base.py", line 100, in import_module
    return importlib.import_module(module, package=package)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/app/apps/modeling/tasks.py", line 27, in <module>
    from gwlfe import gwlfe, parser
ImportError: cannot import name parser
```

Sounds related to the issue they brought up during a call where they were removing the GMS writing bit. Wonder if they did remove it, and didn't put it back.

**Comment by rajadain** [comment]
Ah turns out they casually renamed `parser` to `Parser` here: https://github.com/drexeleds/gwlf-e/commit/5fab6c5

**Comment by rajadain** [comment]
This one may be a little too dense to uncover. This is the line where the error happens: https://github.com/drexeleds/gwlf-e/blame/develop/gwlfe/Parser.py#L1292 but I can't follow the code (or commit history) easily. Not sure if we have the budget to do that.

**Comment by rajadain** [comment]
If we want Drexel to be able to fix this, it would be best if they could run MMW the way we're running it and see the failures that way. For this, they can either install MMW on their end (maybe with our help), or we try to extract a minimal code sample of us running GWLF-E that closely mirrors MMW and send them that. The latter would be more difficult than the former, so should only be attempted if the former doesn't work out.

**Comment by rajadain** [comment]
Above issue is being addressed in https://github.com/drexeleds/gwlf-e/issues/5

**Comment by rajadain** [comment]
That issue has been fixed and merged.

I made a repo to compare the results: https://github.com/rajadain/mmw-gwlfe-comparison

But I'm seeing differences that diverge after the first run. Made https://github.com/drexeleds/gwlf-e/issues/8 to inquire about that.

**Comment by rajadain** [comment]
After the resolution of https://github.com/drexeleds/gwlf-e/issues/5, https://github.com/drexeleds/gwlf-e/issues/8, and https://github.com/drexeleds/gwlf-e/issues/10, all blocking issues have been resolved, and we're seeing a ~75% speedup.

I think #81 is good to merge now. The only missing part is the dependencies situation in #83. We can either merge in #81, and if there are any changes to how dependencies should be installed do them ourselves. Or we can hold off and ask them to implement the changes. I think the former would be more efficient, unless the changes need deep knowledge of the code (which I don't think they will).

To be on the safe side, I'll hold off on merging #81 until I've sat down with operations and talked about #83.

**Comment by rajadain** [comment]
The branch with all the experiments for merging is [`tt/assimilate-drexel-gwlfe`](https://github.com/WikiWatershed/model-my-watershed/tree/tt/assimilate-drexel-gwlfe):

```diff
diff --git a/deployment/ansible/group_vars/all b/deployment/ansible/group_vars/all
index e655a6bc..a078d0a7 100644
--- a/deployment/ansible/group_vars/all
+++ b/deployment/ansible/group_vars/all
@@ -58,3 +58,5 @@ nginx_cache_dir: "/var/cache/nginx"
 observation_api_url: "http://www.wikiwatershed-vs.org/"
 
 enabled_features: ''
+
+numba_version: "0.38.1"
diff --git a/deployment/ansible/roles/model-my-watershed.app/meta/main.yml b/deployment/ansible/roles/model-my-watershed.app/meta/main.yml
index 0f9da49a..cf5bdafc 100644
--- a/deployment/ansible/roles/model-my-watershed.app/meta/main.yml
+++ b/deployment/ansible/roles/model-my-watershed.app/meta/main.yml
@@ -5,6 +5,7 @@ dependencies:
   - { role: "azavea.pip" }
   - { role: "azavea.nodejs" }
   - { role: "azavea.phantomjs" }
+  - { role: "azavea.build-essential" }
   - { role: "model-my-watershed.monitoring", collectd_prefix: "collectd.app.", when: "['test'] | is_not_in(group_names)" }
   - { role: "model-my-watershed.celery" }
   - { role: "model-my-watershed.nginx" }
diff --git a/deployment/ansible/roles/model-my-watershed.app/tasks/dependencies.yml b/deployment/ansible/roles/model-my-watershed.app/tasks/dependencies.yml
index f60daf66..65ae0590 100644
--- a/deployment/ansible/roles/model-my-watershed.app/tasks/dependencies.yml
+++ b/deployment/ansible/roles/model-my-watershed.app/tasks/dependencies.yml
@@ -1,4 +1,7 @@
 ---
+- name: Install numba
+  pip: name=numba version={{ numba_version }}
+
 - name: Install application Python dependencies for development and test
   pip: chdir={{ app_home }}/requirements requirements={{ item }}.txt
   with_items:
diff --git a/deployment/ansible/roles/model-my-watershed.celery-worker/meta/main.yml b/deployment/ansible/roles/model-my-watershed.celery-worker/meta/main.yml
index e5806a72..2d7a1154 100644
--- a/deployment/ansible/roles/model-my-watershed.celery-worker/meta/main.yml
+++ b/deployment/ansible/roles/model-my-watershed.celery-worker/meta/main.yml
@@ -3,5 +3,6 @@ dependencies:
   - { role: "model-my-watershed.base" }
   - { role: "azavea.python", python_development: True }
   - { role: "azavea.pip" }
+  - { role: "azavea.build-essential" }
   - { role: "model-my-watershed.monitoring", collectd_prefix: "collectd.worker.", when: "['test'] | is_not_in(group_names)" }
   - { role: "model-my-watershed.celery" }
diff --git a/deployment/ansible/roles/model-my-watershed.celery-worker/tasks/dependencies.yml b/deployment/ansible/roles/model-my-watershed.celery-worker/tasks/dependencies.yml
index 5bf91d71..d12f9ae2 100644
--- a/deployment/ansible/roles/model-my-watershed.celery-worker/tasks/dependencies.yml
+++ b/deployment/ansible/roles/model-my-watershed.celery-worker/tasks/dependencies.yml
@@ -1,4 +1,7 @@
 ---
+- name: Install numba
+  pip: name=numba version={{ numba_version }}
+
 - name: Install application Python dependencies for development and test
   pip: chdir="{{ celery_dir }}/requirements" requirements={{ item }}.txt
   with_items:
diff --git a/src/mmw/apps/modeling/tasks.py b/src/mmw/apps/modeling/tasks.py
index 666d0722..af5d9304 100644
--- a/src/mmw/apps/modeling/tasks.py
+++ b/src/mmw/apps/modeling/tasks.py
@@ -24,7 +24,7 @@ from apps.modeling.tr55.utils import (aoi_resolution,
                                       )
 
 from tr55.model import simulate_day
-from gwlfe import gwlfe, parser
+from gwlfe import gwlfe, Parser
 
 logger = logging.getLogger(__name__)
 
@@ -343,10 +343,10 @@ def run_gwlfe(model_input, inputmod_hash, watershed_id=None):
     """
     output = to_gms_file(model_input)
 
-    reader = parser.GmsReader(output)
+    reader = Parser.GmsReader(output)
     z = reader.read()
 
-    result = gwlfe.run(z)
+    result, _ = gwlfe.run(z)
     result['inputmod_hash'] = inputmod_hash
     result['watershed_id'] = watershed_id
 
@@ -430,9 +430,9 @@ def to_gms_file(mapshed_data):
     mapshed_areas = [round(a, 1) for a in mapshed_data['Area']]
     mapshed_data['Area'] = mapshed_areas
 
-    pre_z = parser.DataModel(mapshed_data)
+    pre_z = Parser.DataModel(mapshed_data)
     output = StringIO()
-    writer = parser.GmsWriter(output)
+    writer = Parser.GmsWriter(output)
     writer.write(pre_z)
 
     output.seek(0)
diff --git a/src/mmw/mmw/settings/base.py b/src/mmw/mmw/settings/base.py
index 6b312729..808e71f0 100644
--- a/src/mmw/mmw/settings/base.py
+++ b/src/mmw/mmw/settings/base.py
@@ -122,6 +122,8 @@ CELERY_BROKER_URL = 'redis://{0}:{1}/2'.format(
 
 CELERY_IMPORTS = (
     # Submodule task is not always autodiscovered
+    'apps.geoprocessing_api.tasks',
+    'apps.modeling.tasks',
     'apps.modeling.mapshed.tasks',
 )
 CELERY_ACCEPT_CONTENT = ['json']
diff --git a/src/mmw/requirements/base.txt b/src/mmw/requirements/base.txt
index 8edf5ee4..f15f8f0c 100644
--- a/src/mmw/requirements/base.txt
+++ b/src/mmw/requirements/base.txt
@@ -15,7 +15,7 @@ cryptography==2.1.4
 pyOpenSSL==17.4.0
 markdown==2.6.9
 tr55==1.3.0
-gwlf-e==0.6.3
+git+git://github.com/drexeleds/gwlf-e@develop#egg=gwlf-e
 requests[security]==2.9.1
 rollbar==0.13.8
 retry==0.9.1
@@ -24,8 +24,9 @@ https://bitbucket.org/jurko/suds/get/94664ddd46a6.tar.gz#egg=suds-jurko
 django_celery_results==1.0.1
 pandas==0.22.0
 git+git://github.com/emiliom/ulmo@wml_values_md#egg=ulmo
-numpy==1.13.0
+numpy==1.14.5
 hs_restclient==1.2.10
 six==1.11.0
 fiona==1.7.11
 timeout-decorator==0.4.0
+numba==0.38.1
```

I'm going to adopt the bits that worked and excise the rest in a new branch, and merge that. Noting this here for posterity.
